### ISSUE TITLE
Enable SendTask in Chimera

### ISSUE THREAD

**Issue by julianweise** [bptlab/bookshelf-docs#16]
In order to send a rental reminder within our process fragement `Reminder`, we need to setup a mail service (SMTP) and configure Chimera accordingly. Currently, only Gmail accounts are supported in Chimera.

**Tasks:**

- [x] Setup Gmail Account
- [ ] Configure `book-shelf` instance (=> `config.properties`) to use Gmail Account credentials
- [x] SendTask in Gryphon modellieren
- [ ] SendTask in Chimera konfigurieren ("links im Menü"??)

**Comment by tommartensen** [comment]
Gmail account is setup, credentials in Slack

**Comment by tommartensen** [comment]
Blocked by https://github.com/bptlab/chimera/issues/104

**Comment by tommartensen** [comment]
We need to re-deploy this on the bookshelf-chimera instance.
